version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: .docker/dev/Dockerfile
    container_name: infrastructure-example-dev
    image: infrastructure-example-dev:0.0.1
    tty: true
    stdin_open: true
    volumes:
      - .:/app:delegated
      - .docker/dev/.config/pip:/root/.config/pip
      - python:/python
    ports:
      - 80:8080

volumes:
  python:
